spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portfoliodb?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update

  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp/upload
      max-file-size: 100MB
      max-request-size: 100MB