spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://portfoliodb.c0smyxxnegwu.ap-northeast-2.rds.amazonaws.com:3306/portfoliodb?serverTimezone=Asia/Seoul
    username: root
    password: ENC(UJqrmKWUZdgWCwLvVg/DF+BE7lRslsa4)
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp/upload
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
#      static-locations: file:///c:/Temp/upload
      static-locations: file:///tmp/upload
  mvc:
    static-path-pattern: /upload/**

jasypt:
  encryptor:
    bean: jasyptEncryptor